version: '3'

services:
  api:
    container_name: library-api
    build:
      context: ./
      dockerfile: ./.docker/app/Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./data:/app/data
    restart: always
