version: '3'

services:
  api:
    container_name: lms-api
    build:
      context: ./
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - ./data:/app/data
    restart: always
